service:
  name: todo-list

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
     - dev
     - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
  region: sa-east-1
  
functions:
    createTodo:
      handler: src/functions/createTodo.handle
      events:
        - http:
            path: /todos/{userId}
            method: POST
            cors: true
      iamRoleStatements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
    listTodos:
      handler: src/functions/listTodo.handle
      events:
        - http:
            path: /todos/{userId}
            method: GET
            cors: true
      iamRoleStatements:
        - Effect: Allow
          Action:
            - dynamodb:Query

resources:
  Resources:
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE